services:

  queue:
    image: softwaremill/elasticmq:latest
    ports:
      - 9324:9324
      - 9325:9325

    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
